# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.6.3
cache: packages
warnings_are_errors: false
env:
  global:
    - PKG_LIBS = "-llapack"
    - PKG_CXXFLAGS = "-std=c++11"
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglu1-mesa-dev
      - libgsl0-dev
